import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, CalendarClock, CheckCircle2, Gauge, Globe2, ImageIcon, ListChecks, PenLine, Search, Sparkles } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { AdSlot } from "@/components/AdSlot";
import { useAuth } from "@/hooks/useAuth";

export const Route = createFileRoute("/")({
  head: () => ({ meta: [
    { title: "BlogPilot AI — SEO blog content on autopilot" },
    { name: "description", content: "Plan, draft and schedule SEO blog posts for every niche. BlogPilot AI turns keyword research into a publish-ready content queue for your Blogger site." },
    { name: "robots", content: "index, follow, max-image-preview:large" },
    { property: "og:title", content: "BlogPilot AI — SEO blog content on autopilot" },
    { property: "og:description", content: "Turn keyword research into a publish-ready content queue for your blog, in any niche and language." },
    { property: "og:type", content: "website" },
    { property: "og:image", content: "/blogpilot-dashboard-preview.svg" },
    { name: "twitter:card", content: "summary_large_image" },
  ] }), component: Landing,
});

const features = [
  { icon: Search, title: "Keyword-led planning", body: "Pick a niche, country and language. BlogPilot builds a topic queue around the searches that actually convert." },
  { icon: ListChecks, title: "A real content queue", body: "Every topic carries an outline, SEO title, meta description and status so nothing stalls at half-done." },
  { icon: Globe2, title: "Multi-market ready", body: "English, Bahasa Melayu, Indonesian, Spanish and more — with country targeting per blog." },
  { icon: Gauge, title: "Cadence you control", body: "Set posts per week and article length once; the plan paces itself to match." },
  { icon: PenLine, title: "AI drafting", body: "One click turns an approved outline into a full, on-brand article draft." },
  { icon: CalendarClock, title: "Auto-publish to Blogger", body: "Autopilot writes, creates the required AI cover image and publishes the complete post on schedule." },
];
const plans = [
  { name: "Free", price: "RM0", note: "forever", perks: ["1 blog", "Topic planning + outlines", "5 AI drafts / month", "Manual publishing"], cta: "Start free", highlight: false },
  { name: "Pro", price: "RM49", note: "per month", perks: ["5 blogs", "Unlimited AI drafts", "Autopilot daily publishing", "AI cover images", "Priority support"], cta: "Start free, upgrade later", highlight: true },
];
const faqs = [
  { q: "Do I need my own AI key?", a: "No. Drafting, topic planning and cover images are built in — just sign in with Google." },
  { q: "Which blog platforms are supported?", a: "Blogger is supported today: connect your Google account, pick a blog, and posts publish straight to it." },
  { q: "What does autopilot actually do?", a: "It picks the next topic, writes the article, creates the required AI featured image, prepares SEO metadata and publishes the complete post on your chosen cadence." },
  { q: "Can I edit before anything goes live?", a: "Yes. For a manual Autopilot run, BlogPilot shows the article and image settings first. Turn automatic publishing off if you want the generated package to wait as a draft." },
];
const steps = [
  { n: "01", title: "Add your blog", body: "Name it, drop the URL, choose niche, market and tone." },
  { n: "02", title: "Review the recipe", body: "Choose article length, voice, AI image ratio and image style before a manual Autopilot run." },
  { n: "03", title: "Generate and ship", body: "BlogPilot writes the article, creates its AI image and publishes the complete package to Blogger." },
];

function Landing() {
  const { session, loading } = useAuth(); const signedIn = !loading && !!session;
  const schema = { "@context": "https://schema.org", "@type": "SoftwareApplication", name: "BlogPilot AI", applicationCategory: "BusinessApplication", operatingSystem: "Web", description: "SEO content planning, drafting, AI image generation and Blogger publishing automation.", offers: [{ "@type": "Offer", price: "0", priceCurrency: "MYR", name: "Free" }, { "@type": "Offer", price: "49", priceCurrency: "MYR", name: "Pro" }] };
  return <div className="min-h-screen">
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }} />
    <header className="sticky top-0 z-20 border-b border-border bg-background/85 backdrop-blur"><div className="mx-auto flex max-w-6xl items-center gap-4 px-4 py-3"><Link to="/" className="font-display text-sm font-bold tracking-tight">BlogPilot<span className="text-primary">.</span>AI</Link><nav className="hidden flex-1 items-center gap-4 text-sm text-muted-foreground md:flex"><Link to="/guides" className="hover:text-foreground">Guides</Link><Link to="/tools/blog-title-generator" className="hover:text-foreground">Free title generator</Link><Link to="/about" className="hover:text-foreground">About</Link><Link to="/help" className="hover:text-foreground">Help</Link></nav><div className="ml-auto flex items-center gap-2">{signedIn?<Button size="sm" asChild><Link to="/dashboard">Go to dashboard</Link></Button>:<><Button variant="ghost" size="sm" asChild><Link to="/auth" search={{next:undefined}}>Sign in</Link></Button><Button size="sm" asChild><Link to="/auth" search={{next:undefined}}>Get started</Link></Button></>}</div></div></header>
    <main>
      <section className="grid-backdrop border-b border-border"><div className="mx-auto grid max-w-6xl items-center gap-12 px-4 py-16 sm:py-24 lg:grid-cols-[0.95fr_1.05fr] lg:py-28"><div><Badge variant="outline" className="border-primary/40 text-primary">Free to start</Badge><h1 className="font-display mt-5 max-w-3xl text-4xl font-bold leading-[1.05] tracking-tight sm:text-6xl">SEO blog content, planned and shipped on <span className="text-primary">autopilot</span>.</h1><p className="mt-5 max-w-xl text-base text-muted-foreground sm:text-lg">BlogPilot AI turns a niche and a target market into a working content engine — article, SEO metadata and AI featured image included — so your Blogger site keeps moving.</p><div className="mt-8 flex flex-wrap items-center gap-3"><Button size="lg" asChild><Link to="/auth" search={{next:undefined}}>Start planning free<ArrowRight aria-hidden /></Link></Button><Button size="lg" variant="secondary" asChild><Link to="/tools/blog-title-generator"><Sparkles className="size-4" aria-hidden />Try free SEO title tool</Link></Button></div><p className="text-eyebrow mt-6">No card required · Google sign-in · 12 niches · 8 languages</p></div><div className="relative"><div className="absolute -inset-6 -z-10 rounded-[2.5rem] bg-primary/5 blur-2xl"/><div className="overflow-hidden rounded-2xl border border-border bg-card p-2 shadow-2xl shadow-black/10"><img src="/blogpilot-dashboard-preview.svg" alt="BlogPilot AI dashboard showing the Autopilot publishing workflow" className="h-auto w-full rounded-xl" loading="eager" /></div><div className="absolute -bottom-4 left-4 flex items-center gap-2 rounded-full border border-border bg-background/95 px-4 py-2 text-xs font-medium shadow-lg backdrop-blur"><CheckCircle2 className="size-4 text-primary" aria-hidden />Article + AI image + SEO, one workflow</div></div></div></section>

      <section className="mx-auto max-w-6xl px-4 py-10 sm:py-12"><div className="surface-panel grid gap-5 p-6 sm:p-8 lg:grid-cols-[1fr_auto] lg:items-center"><div><div className="flex items-center gap-2"><Sparkles className="size-5 text-primary" aria-hidden /><p className="text-eyebrow">Free SEO tool</p></div><h2 className="font-display mt-2 text-2xl font-bold tracking-tight">Need title ideas before you sign up?</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-muted-foreground sm:text-base">Use the free SEO Blog Title Generator to turn any topic or niche into eight search-focused title ideas with ready-to-use meta descriptions. No account required.</p></div><Button size="lg" asChild><Link to="/tools/blog-title-generator">Open free title generator<ArrowRight aria-hidden /></Link></Button></div></section>

      <section className="mx-auto max-w-6xl px-4 py-16 sm:py-20"><p className="text-eyebrow">What you get</p><h2 className="font-display mt-2 text-2xl font-bold tracking-tight sm:text-3xl">Everything a one-person publishing team needs</h2><div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{features.map((f)=><article key={f.title} className="surface-panel p-5"><f.icon className="size-5 text-primary" aria-hidden/><h3 className="font-display mt-4 text-base font-semibold">{f.title}</h3><p className="mt-2 text-sm text-muted-foreground">{f.body}</p></article>)}</div></section>

      <section className="border-y border-border bg-card/40"><div className="mx-auto grid max-w-6xl items-center gap-10 px-4 py-16 sm:py-20 lg:grid-cols-2"><div className="order-2 lg:order-1"><div className="overflow-hidden rounded-2xl border border-border bg-background p-2 shadow-xl shadow-black/5"><img src="/blogpilot-ai-publishing.svg" alt="BlogPilot AI content package with AI image, SEO meta description and Blogger publishing" className="h-auto w-full rounded-xl" loading="lazy" /></div></div><div className="order-1 lg:order-2"><div className="flex size-10 items-center justify-center rounded-xl bg-primary/10"><ImageIcon className="size-5 text-primary" aria-hidden /></div><p className="text-eyebrow mt-5">A complete post, not just text</p><h2 className="font-display mt-2 text-2xl font-bold tracking-tight sm:text-3xl">Every Autopilot article ships as a visual content package.</h2><p className="mt-4 max-w-xl text-sm leading-6 text-muted-foreground sm:text-base">Before a manual run, review the writing and image recipe. BlogPilot then writes the article, suggests the search description, creates the featured image in your chosen style and only publishes when the image is ready.</p><div className="mt-6 grid gap-3 sm:grid-cols-2"><div className="surface-panel p-4"><p className="text-sm font-semibold">Image control</p><p className="mt-1 text-xs text-muted-foreground">16:9, 4:3, 1:1 or custom · Auto, realistic, 2D or 3D style.</p></div><div className="surface-panel p-4"><p className="text-sm font-semibold">SEO-ready metadata</p><p className="mt-1 text-xs text-muted-foreground">AI-suggested meta search descriptions are kept within 150 characters.</p></div></div></div></div></section>

      <div className="mx-auto max-w-6xl px-4 py-8"><AdSlot id="landing-mid" format="leaderboard" /></div>
      <section className="border-y border-border bg-card/40"><div className="mx-auto max-w-6xl px-4 py-16 sm:py-20"><p className="text-eyebrow">How it works</p><h2 className="font-display mt-2 text-2xl font-bold tracking-tight sm:text-3xl">Three steps from idea to complete Blogger post</h2><ol className="mt-8 grid gap-4 sm:grid-cols-3">{steps.map((s)=><li key={s.n} className="surface-panel p-5"><span className="font-display text-primary text-2xl font-bold">{s.n}</span><h3 className="font-display mt-3 text-base font-semibold">{s.title}</h3><p className="mt-2 text-sm text-muted-foreground">{s.body}</p></li>)}</ol></div></section>
      <section className="mx-auto max-w-6xl px-4 py-16 sm:py-20"><p className="text-eyebrow">Pricing</p><h2 className="font-display mt-2 text-2xl font-bold tracking-tight sm:text-3xl">Simple plans, no card to start</h2><div className="mt-8 grid gap-4 sm:grid-cols-2">{plans.map((p)=><div key={p.name} className={`surface-panel p-6 ${p.highlight?"border-primary/50":""}`}><div className="flex items-center gap-2"><h3 className="font-display text-lg font-semibold">{p.name}</h3>{p.highlight&&<Badge>Most popular</Badge>}</div><p className="font-display mt-3 text-3xl font-bold">{p.price} <span className="text-sm font-normal text-muted-foreground">{p.note}</span></p><ul className="mt-4 space-y-2 text-sm text-muted-foreground">{p.perks.map((perk)=><li key={perk}>· {perk}</li>)}</ul><Button className="mt-6" variant={p.highlight?"default":"secondary"} asChild><Link to="/auth" search={{next:undefined}}>{p.cta}</Link></Button></div>)}</div></section>
      <section className="border-t border-border bg-card/40"><div className="mx-auto max-w-6xl px-4 py-16 sm:py-20"><p className="text-eyebrow">FAQ</p><h2 className="font-display mt-2 text-2xl font-bold tracking-tight sm:text-3xl">Questions people ask first</h2><div className="mt-8 grid gap-4 sm:grid-cols-2">{faqs.map((item)=><div key={item.q} className="surface-panel p-5"><h3 className="font-display text-base font-semibold">{item.q}</h3><p className="mt-2 text-sm text-muted-foreground">{item.a}</p></div>)}</div><Button className="mt-6" variant="outline" asChild><Link to="/help">View all help topics</Link></Button></div></section>
      <section className="mx-auto max-w-6xl px-4 py-20"><div className="surface-panel grid gap-8 overflow-hidden p-8 sm:p-12 lg:grid-cols-[1fr_auto] lg:items-center"><div><h2 className="font-display max-w-2xl text-2xl font-bold tracking-tight sm:text-4xl">Your next 30 blog posts are one sign-in away.</h2><p className="mt-4 max-w-xl text-sm text-muted-foreground sm:text-base">Set up your first blog in under a minute — planning, AI drafting, featured images and Blogger auto-publishing are built into one workflow.</p></div><Button size="lg" asChild><Link to="/auth" search={{next:undefined}}>Create your workspace<ArrowRight aria-hidden /></Link></Button></div></section>
    </main>
    <footer className="border-t border-border"><div className="mx-auto max-w-6xl px-4 py-8"><div className="flex flex-wrap items-center gap-x-5 gap-y-2 text-sm text-muted-foreground"><span className="font-display font-bold tracking-tight text-foreground">BlogPilot<span className="text-primary">.</span>AI</span><Link to="/guides" className="hover:text-foreground">Guides</Link><Link to="/about" className="hover:text-foreground">About</Link><Link to="/help" className="hover:text-foreground">Help</Link><Link to="/privacy" className="hover:text-foreground">Privacy</Link><Link to="/terms" className="hover:text-foreground">Terms</Link><Link to="/contact" className="hover:text-foreground">Contact</Link><span className="ml-auto">© {new Date().getFullYear()} BlogPilot AI. All rights reserved.</span></div></div></footer>
  </div>;
}
