/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedArticlesRouteImport } from './routes/_authenticated/articles'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedQueueRouteImport } from './routes/_authenticated/queue'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as SitemapXmlRouteImport } from './routes/sitemap.xml'
import { Route as AuthenticatedBloggerCallbackRouteImport } from './routes/_authenticated/blogger.callback'
import { Route as ApiPublicCronAutopilotRouteImport } from './routes/api/public/cron/autopilot'
import { Route as ApiPublicPostImagePostIdRouteImport } from './routes/api/public/post-image/$postId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedArticlesRoute = AuthenticatedArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQueueRoute = AuthenticatedQueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const SitemapXmlRoute = SitemapXmlRouteImport.update({
  id: '/sitemap/xml',
  path: '/sitemap/xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedBloggerCallbackRoute =
  AuthenticatedBloggerCallbackRouteImport.update({
    id: '/blogger/callback',
    path: '/blogger/callback',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicCronAutopilotRoute = ApiPublicCronAutopilotRouteImport.update({
  id: '/api/public/cron/autopilot',
  path: '/api/public/cron/autopilot',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPostImagePostIdRoute =
  ApiPublicPostImagePostIdRouteImport.update({
    id: '/api/public/post-image/$postId',
    path: '/api/public/post-image/$postId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/articles': typeof AuthenticatedArticlesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/queue': typeof AuthenticatedQueueRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/blogger/callback': typeof AuthenticatedBloggerCallbackRoute
  '/api/public/cron/autopilot': typeof ApiPublicCronAutopilotRoute
  '/api/public/post-image/$postId': typeof ApiPublicPostImagePostIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/articles': typeof AuthenticatedArticlesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/queue': typeof AuthenticatedQueueRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/blogger/callback': typeof AuthenticatedBloggerCallbackRoute
  '/api/public/cron/autopilot': typeof ApiPublicCronAutopilotRoute
  '/api/public/post-image/$postId': typeof ApiPublicPostImagePostIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/articles': typeof AuthenticatedArticlesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/queue': typeof AuthenticatedQueueRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/_authenticated/blogger/callback': typeof AuthenticatedBloggerCallbackRoute
  '/api/public/cron/autopilot': typeof ApiPublicCronAutopilotRoute
  '/api/public/post-image/$postId': typeof ApiPublicPostImagePostIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/articles'
    | '/dashboard'
    | '/queue'
    | '/settings'
    | '/sitemap/xml'
    | '/blogger/callback'
    | '/api/public/cron/autopilot'
    | '/api/public/post-image/$postId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/articles'
    | '/dashboard'
    | '/queue'
    | '/settings'
    | '/sitemap/xml'
    | '/blogger/callback'
    | '/api/public/cron/autopilot'
    | '/api/public/post-image/$postId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/articles'
    | '/_authenticated/dashboard'
    | '/_authenticated/queue'
    | '/_authenticated/settings'
    | '/sitemap/xml'
    | '/_authenticated/blogger/callback'
    | '/api/public/cron/autopilot'
    | '/api/public/post-image/$postId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  SitemapXmlRoute: typeof SitemapXmlRoute
  ApiPublicCronAutopilotRoute: typeof ApiPublicCronAutopilotRoute
  ApiPublicPostImagePostIdRoute: typeof ApiPublicPostImagePostIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/articles': {
      id: '/_authenticated/articles'
      path: '/articles'
      fullPath: '/articles'
      preLoaderRoute: typeof AuthenticatedArticlesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/queue': {
      id: '/_authenticated/queue'
      path: '/queue'
      fullPath: '/queue'
      preLoaderRoute: typeof AuthenticatedQueueRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/sitemap/xml': {
      id: '/sitemap/xml'
      path: '/sitemap/xml'
      fullPath: '/sitemap/xml'
      preLoaderRoute: typeof SitemapXmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/blogger/callback': {
      id: '/_authenticated/blogger/callback'
      path: '/blogger/callback'
      fullPath: '/blogger/callback'
      preLoaderRoute: typeof AuthenticatedBloggerCallbackRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/cron/autopilot': {
      id: '/api/public/cron/autopilot'
      path: '/api/public/cron/autopilot'
      fullPath: '/api/public/cron/autopilot'
      preLoaderRoute: typeof ApiPublicCronAutopilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/post-image/$postId': {
      id: '/api/public/post-image/$postId'
      path: '/api/public/post-image/$postId'
      fullPath: '/api/public/post-image/$postId'
      preLoaderRoute: typeof ApiPublicPostImagePostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedArticlesRoute: typeof AuthenticatedArticlesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedQueueRoute: typeof AuthenticatedQueueRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedBloggerCallbackRoute: typeof AuthenticatedBloggerCallbackRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedArticlesRoute: AuthenticatedArticlesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedQueueRoute: AuthenticatedQueueRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedBloggerCallbackRoute: AuthenticatedBloggerCallbackRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  SitemapXmlRoute: SitemapXmlRoute,
  ApiPublicCronAutopilotRoute: ApiPublicCronAutopilotRoute,
  ApiPublicPostImagePostIdRoute: ApiPublicPostImagePostIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
